name: Remove labels when PR updated

on:
  pull_request_target:
    types: [synchronize]
    # optional: restrict to a branch
    branches: [develop]

permissions:
  issues: write
  pull-requests: write

jobs:
  remove-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Remove all labels from PR when new commits are pushed
        uses: mondeja/remove-labels-gh-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            ci:approved-to-run