name: Remove labels when PR updated

on:
  pull_request_target:
    types: [synchronize]
    # optional: restrict to a branch
    branches: [develop]

permissions:
  issues: write
  pull-requests: read
  contents: read

jobs:
  remove-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Remove all labels from PR when new commits are pushed
        uses: actions/github-script@v6
        with:
          script: |
            const pr = github.context.payload.pull_request;
            if (!pr) throw new Error('No pull_request in context');
            await github.rest.issues.removeAllLabels({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              issue_number: pr.number
            });
            console.log(`Removed all labels from PR #${pr.number}`);