name: Deploy (GitHub Pages)
on:
  push:
    branches: [develop]
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r ci/requirements.txt

      - name: Build Jupyter Book
        run: jupyter-book build .

      # Publish production site to gh-pages but keep PR previews
      - name: Publish to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _build/html
          clean-exclude: pr-preview/ # <-- don't delete previews
          force: false # safer history; keeps siblings
