name: Comment when PR preview is ready

on:
  workflow_run:
    workflows: ['PR Artifact Preview']   # must equal your PR preview workflow name
    types: [completed]

permissions:
  issues: write
  contents: read
  pull-requests: read
  actions: read

jobs:
  comment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v8
        with:
          script: |
            const run = context.payload.workflow_run;
            const { owner, repo } = context.repo;

            // Only handle preview runs from pull_request events
            if (run.event !== 'pull_request') {
              core.notice(`workflow_run event was '${run.event}', not 'pull_request' — skipping comment.`);
              return;
            }

            let prNumber = run.pull_requests?.[0]?.number;

            // --- 1) Best source: PRs attached to this workflow run ---
            if (!prNumber) {
              const prsForRun = await github.rest.actions.listWorkflowRunPullRequests({
                owner, repo, run_id: run.id,
              });
              if (prsForRun.data?.length > 0) {
                prNumber = prsForRun.data[0].number;
                core.notice(`Found PR via actions.listWorkflowRunPullRequests: #${prNumber}`);
              }
            }

            // --- 2) Next best: find by head repo + branch (works for forks) ---
            if (!prNumber) {
              // Try to reconstruct "<forkOwner>:<branch>"
              // run.head_repository is sometimes present on the run payload;
              // if not, fall back to assuming same repo owner (works for same-repo PRs).
              let headOwner = run.head_repository?.owner?.login;
              const headBranch = run.head_branch;
              if (!headOwner) {
                // Try to refetch the run with expanded fields
                try {
                  const runRef = await github.rest.actions.getWorkflowRun({
                    owner, repo, run_id: run.id,
                  });
                  headOwner = runRef.data.head_repository?.owner?.login;
                } catch (e) {
                  core.notice(`Could not refetch run for head_repository: ${e.message}`);
                }
              }
              if (!headOwner) headOwner = owner; // same-repo fallback

              if (headOwner && headBranch) {
                const headRef = `${headOwner}:${headBranch}`;
                const list = await github.rest.pulls.list({
                  owner, repo, state: 'all', head: headRef, per_page: 1,
                });
                if (list.data?.length > 0) {
                  prNumber = list.data[0].number;
                  core.notice(`Found PR via pulls.list head=${headRef}: #${prNumber}`);
                }
              } else {
                core.notice('head_owner/head_branch missing; cannot use pulls.list head filter.');
              }
            }

            // --- 3) Last resort: search by head SHA in this repo (may fail for forks) ---
            if (!prNumber) {
              const search = await github.rest.search.issuesAndPullRequests({
                q: `repo:${owner}/${repo} is:pr sha:${run.head_sha}`,
                per_page: 1,
              });
              if (search.data.total_count > 0) {
                prNumber = search.data.items[0].number;
                core.notice(`Found PR via search.sha: #${prNumber}`);
              }
            }

            if (!prNumber) {
              core.notice('Could not determine PR number for this run — skipping comment.');
              return;
            }

            const runUrl = run.html_url || `https://github.com/${owner}/${repo}/actions/runs/${run.id}`;

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: [
                "🔎 **Preview artifact is ready.**",
                "",
                `• Open **[this workflow run](${runUrl})** → **Artifacts** → download **pr-preview-site** (or the Pages artifact).`,
                "• Unzip and open \`index.html\` locally to review the site.",
                "",
                "_Note: Notebook execution is disabled in PR previews for security._"
              ].join("\n")
            });
