name: Remove preview-ok on update
on:
  pull_request_target:
    types: [synchronize]

permissions:
  pull-requests: write

jobs:
  remove-label:
    if: contains(join(github.event.pull_request.labels.*.name, ','), 'preview-ok')
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: preview-ok
